# Generated by Django 5.1.1 on 2026-05-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
