# Generated by Django 5.2.13 on 2026-05-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_skill_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('deleted', models.BooleanField(default=False)),
                ('project_type', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('bid_period_days', models.IntegerField(blank=True, null=True)),
                ('free_bids_expire_at', models.DateTimeField(blank=True, null=True)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bid_count', models.IntegerField(blank=True, null=True)),
                ('bid_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('urgent', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('nonpublic', models.BooleanField(default=False)),
                ('enterprise', models.BooleanField(default=False)),
                ('premium', models.BooleanField(default=False)),
                ('sealed', models.BooleanField(default=False)),
                ('nda_required', models.BooleanField(default=False)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
