# Generated by Django 5.2.13 on 2026-06-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_freelancerskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='freelancer_skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='app.freelancerskill'),
        ),
    ]
