# Generated by Django 5.2.13 on 2026-06-28 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_address_company_role_roletask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='ending_salary',
            new_name='ending_pay',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='starting_salary',
            new_name='starting_pay',
        ),
    ]
