# Generated by Django 5.2.13 on 2026-06-28 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_ending_salary_role_ending_pay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='employment_type',
        ),
    ]
