# Generated by Django 5.2.13 on 2026-06-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_role_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='pay_frequency',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('monthly', 'Monthly')], max_length=20),
        ),
    ]
