# Generated by Django 5.2.13 on 2026-06-28 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_role_pay_frequency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='FreelancerProject',
        ),
    ]
