# Generated by Django 5.2.13 on 2026-06-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_project_projecttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='skills',
            field=models.ManyToManyField(blank=True, to='app.skill'),
        ),
    ]
