# Generated by Django 5.2.13 on 2026-06-28 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_role_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('resume_ready', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app.education')),
                ('skills', models.ManyToManyField(blank=True, related_name='courses', to='app.skill')),
            ],
        ),
    ]
