# Generated by Django 5.2.13 on 2026-07-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_profilesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='resume_ready',
            field=models.BooleanField(default=False),
        ),
    ]
