# Generated by Django 5.2.13 on 2026-08-30 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_company_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(blank=True)),
                ('max_skills', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(blank=True, null=True)),
                ('listed', models.BooleanField(blank=True, null=True)),
                ('updated', models.DateField(blank=True, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.platform')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.skill')),
            ],
        ),
        migrations.AddField(
            model_name='platform',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='platforms', through='app.PlatformSkill', to='app.skill'),
        ),
        migrations.AddConstraint(
            model_name='platformskill',
            constraint=models.UniqueConstraint(fields=('platform', 'skill'), name='unique_platform_skill'),
        ),
    ]
