# Generated by Django 5.2.13 on 2026-09-02 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_platform_platformskill_platform_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roletask',
            name='skills',
        ),
    ]
