# Generated by Django 5.2.13 on 2026-09-02 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_roletask_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='skills',
        ),
    ]
