# Generated by Django 5.2.13 on 2026-09-04 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_skill_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('updated', models.DateField(blank=True, null=True)),
                ('wait', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='app.feature')),
            ],
        ),
    ]
