# Generated by Django 5.2.13 on 2026-09-04 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_feature_featurelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(blank=True, null=True)),
                ('updated', models.DateField(blank=True, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.feature')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.platform')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('platform', 'feature'), name='unique_platform_feature')],
            },
        ),
    ]
