# Generated by Django 5.2.13 on 2026-09-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_platformfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='platforms', through='app.PlatformFeature', to='app.feature'),
        ),
    ]
