# Generated by Django 5.2.13 on 2026-09-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_platform_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurelink',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
