# Generated by Django 5.2.13 on 2026-09-04 23:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_peer'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='peers', to='app.company'),
        ),
        migrations.AddField(
            model_name='peer',
            name='referrals',
            field=models.ManyToManyField(blank=True, related_name='referred_by', to='app.peer'),
        ),
        migrations.CreateModel(
            name='PeerConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_date', models.DateField(blank=True, null=True)),
                ('meeting_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connects', to='app.peer')),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('peer_connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='app.peerconnect')),
            ],
        ),
    ]
