# Generated by Django 5.2.13 on 2026-09-06 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_peer_companies_peer_referrals_peerconnect_direction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peer',
            new_name='Professional',
        ),
        migrations.RenameModel(
            old_name='PeerConnect',
            new_name='ProfessionalConnect',
        ),
        migrations.RenameField(
            model_name='direction',
            old_name='peer_connect',
            new_name='meeting',
        ),
        migrations.RenameField(
            model_name='professionalconnect',
            old_name='peer',
            new_name='person',
        ),
    ]
