# Generated by Django 5.2.13 on 2026-09-06 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_rename_peer_professional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalconnect',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connects', to='app.professional'),
        ),
    ]
