# Generated by Django 5.2.13 on 2026-09-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_professionalconnect_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
