# Generated by Django 5.2.13 on 2026-09-09 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_company_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalconnect',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
