# Generated by Django 5.2.13 on 2026-09-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_professionalconnect_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalconnect',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
