# Generated by Django 5.2.13 on 2026-09-10 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_professionalconnect_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direction',
            old_name='meeting',
            new_name='connect',
        ),
    ]
