# Generated by Django 5.2.13 on 2026-09-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_rename_meeting_direction_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalconnect',
            name='google_invite_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='professionalconnect',
            name='google_meeting_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='professionalconnect',
            name='meeting_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
