# Generated by Django 5.2.13 on 2026-09-13 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_professionalconnect_google_invite_event_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalconnect',
            old_name='person',
            new_name='professional',
        ),
    ]
