# Generated by Django 5.2.13 on 2026-09-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_rename_person_professionalconnect_professional'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfessionalConnect',
            new_name='Connect',
        ),
    ]
