# Generated by Django 5.2.13 on 2026-09-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_rename_professionalconnect_connect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='app.company'),
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('linkedin_url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('wait', models.DurationField(blank=True, null=True)),
                ('companies', models.ManyToManyField(blank=True, related_name='recruiters', to='app.company')),
                ('referrals', models.ManyToManyField(blank=True, related_name='referred_by', to='app.recruiter')),
            ],
        ),
    ]
