# Generated by Django 5.2.13 on 2026-09-13 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_professional_companies_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connects', to='app.recruiter'),
        ),
    ]
