# Generated by Django 5.2.13 on 2026-09-18 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_connect_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('apply_to', models.BooleanField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_paths', to='app.company')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_paths', to='app.platform')),
                ('search_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_paths', to='app.searchterm')),
            ],
        ),
        migrations.CreateModel(
            name='SearchObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job_posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_observations', to='app.jobposting')),
                ('search_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='app.searchpath')),
            ],
        ),
        migrations.AddConstraint(
            model_name='searchpath',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('platform__isnull', False), ('company__isnull', True)), models.Q(('platform__isnull', True), ('company__isnull', False)), _connector='OR'), name='search_path_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='searchpath',
            constraint=models.UniqueConstraint(condition=models.Q(('platform__isnull', False)), fields=('platform', 'search_term'), name='unique_platform_search_path', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='searchpath',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'search_term'), name='unique_company_search_path', nulls_distinct=False),
        ),
    ]
