# Generated by Django 5.2.13 on 2026-09-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_jobposting_searchterm_searchpath_searchobservation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchpath",
            name="search_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="search_paths",
                to="app.searchterm",
            ),
        ),
    ]
