# Generated by Django 5.2.13 on 2026-09-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_searchpath_search_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='job_search_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='supports_job_search_terms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='job_search_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
