# Generated by Django 5.2.13 on 2026-09-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_company_job_search_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchpath',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
