# Generated by Django 5.2.13 on 2026-09-19 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_searchpath_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchobservation',
            name='search_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='app.searchpath'),
        ),
    ]
