# Generated by Django 5.2.13 on 2026-09-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_searchobservation_search_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='ai_recommend_apply',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
