# Generated by Django 5.2.13 on 2026-09-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_jobposting_ai_recommend_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='ai_explanation',
            field=models.TextField(blank=True),
        ),
    ]
