# Generated by Django 5.2.13 on 2026-10-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_jobposting_ai_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
