# Generated by Django 5.2.13 on 2026-10-03 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_jobposting_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('submitted', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='app.company')),
                ('job_posting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='app.jobposting')),
            ],
        ),
    ]
