# Generated by Django 5.2.13 on 2026-10-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='stop_reason',
            field=models.CharField(blank=True, choices=[('application_issue', 'Application Issue'), ('recent_application', 'Recently Applied to Company'), ('other', 'Other')], max_length=30),
        ),
    ]
