# Generated by Django 5.2.13 on 2026-10-08 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_application_stop_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=255, unique=True)),
                ('gmail_thread_id', models.CharField(blank=True, max_length=255)),
                ('email_type', models.CharField(choices=[('confirmation', 'Application Confirmation'), ('assessment', 'Online Assessment Request'), ('interview', 'Interview Request'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('other', 'Other')], default='other', max_length=30)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('sender', models.EmailField(max_length=254)),
                ('recipients', models.TextField(blank=True)),
                ('received_at', models.DateTimeField()),
                ('body', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='app.application')),
            ],
        ),
    ]
