# Generated by Django 5.2.13 on 2026-10-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_applicationemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationemail',
            name='direction',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], default='incoming', max_length=10),
        ),
        migrations.AlterField(
            model_name='applicationemail',
            name='email_type',
            field=models.CharField(choices=[('confirmation', 'Application Confirmation'), ('assessment', 'Online Assessment Request'), ('interview', 'Interview Request'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('my_response', 'My Response'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
