# Generated by Django 5.2.13 on 2026-10-11 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_applicationemail_direction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('general', 'General Interview'), ('technical', 'Technical Interview'), ('behavioral', 'Behavioral Interview')], default='general', max_length=20)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_practice_sessions', to='app.application')),
                ('interview_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_practice_sessions', to='app.applicationemail')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewPracticeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.interviewpracticesession')),
            ],
            options={
                'ordering': ['created', 'pk'],
            },
        ),
    ]
