# Generated by Django 5.2.13 on 2026-10-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_interviewpracticesession_interviewpracticemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='outcome',
            field=models.CharField(choices=[('in_process', 'In Process'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='in_process', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Submitted'), (2, 'Confirmed'), (3, 'Assessed'), (4, 'Interviewed')], default=1),
        ),
    ]
